services:
  frontend:
    container_name: voting-app
    build:
      context: .
    image: voting-app
    ports:
      - "5051:5050"
    environment:
      - PORT=5050
      - MONGODB_URI=mongodb://admin:admin123@mongodb-server:27017/voting-app-db?authSource=admin
    depends_on:
      - mongodb-server
  mongodb-server:
    container_name: mongodb-server
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123

